// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDMwt3hHcOi8XPkH8cxRtxWA-HwcrPkbs',
    appId: '1:67087405396:web:2cc89bd84c88cdb09878c1',
    messagingSenderId: '67087405396',
    projectId: 'monon-community',
    authDomain: 'monon-community.firebaseapp.com',
    storageBucket: 'monon-community.firebasestorage.app',
    measurementId: 'G-F9EMERJK0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-62_kUSvSmDJrMONC4afJTC9ORxS8daY',
    appId: '1:67087405396:android:76493c24a7113c009878c1',
    messagingSenderId: '67087405396',
    projectId: 'monon-community',
    storageBucket: 'monon-community.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYzigKMh8SGLFRIFwj-jO439-Nwc4wxGc',
    appId: '1:67087405396:ios:18eed0e0175c684e9878c1',
    messagingSenderId: '67087405396',
    projectId: 'monon-community',
    storageBucket: 'monon-community.firebasestorage.app',
    iosBundleId: 'com.monon.community',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYzigKMh8SGLFRIFwj-jO439-Nwc4wxGc',
    appId: '1:67087405396:ios:667b8b9c506a904d9878c1',
    messagingSenderId: '67087405396',
    projectId: 'monon-community',
    storageBucket: 'monon-community.firebasestorage.app',
    iosBundleId: 'com.example.monon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDMwt3hHcOi8XPkH8cxRtxWA-HwcrPkbs',
    appId: '1:67087405396:web:0289664a12c7fca39878c1',
    messagingSenderId: '67087405396',
    projectId: 'monon-community',
    authDomain: 'monon-community.firebaseapp.com',
    storageBucket: 'monon-community.firebasestorage.app',
    measurementId: 'G-F18VMKDT4D',
  );
}
